services:

    wearejust_form.form_type.readonly_type:
        class: Wearejust\FormBundle\Form\Type\ReadonlyType
        tags:
            - { name: form.type }

    wearejust_form.form_extension.image_type_extension:
        class: Wearejust\FormBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Presta\ImageBundle\Form\Type\ImageType }

    wearejust_form.routing.presta_image_routing_loader:
        class: Wearejust\FormBundle\Routing\PrestaImageRoutingLoader
        arguments: ['%kernel.bundles%']
        tags:
            - { name: routing.loader }

    wearejust_form.editorjs.upload.listener:
        class: Wearejust\FormBundle\EventListener\EditorJSUploadListener
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }

    wearejust_form.twig_extension.block_extension:
        class: Wearejust\FormBundle\Twig\Extension\BlockExtension
        tags:
            - { name: twig.extension }
